name: esc_pos_printer_plus
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 0.0.3
homepage: https://github.com/brasizza/esc_pos_printer.git

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  charset_converter: ^2.1.1
  
  esc_pos_utils_plus: ^2.0.3
  flutter:
    sdk: flutter
  image: ^4.0.02

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
